execute @e[type=dragonmountsplus:forest_dragon_egg,scores={Timer=6000}] ~~~ detect ~ ~-1 ~ minecraft:cherry_log 0 execute @s ~ ~ ~ detect ~1 ~-1 ~ minecraft:cherry_log 0 execute @s ~ ~ ~ detect ~-1 ~-1 ~ minecraft:cherry_log 0 execute @s ~ ~ ~ detect ~ ~-1 ~1 minecraft:cherry_log 0 execute @s ~ ~ ~ detect ~ ~-1 ~-1 minecraft:cherry_log 0 execute @s ~ ~ ~ detect ~1 ~-1 ~1 minecraft:cherry_log 0 execute @s ~ ~ ~ detect ~-1 ~-1 ~1 minecraft:cherry_log 0 execute @s ~ ~ ~ detect ~1 ~-1 ~-1 minecraft:cherry_log 0 execute @s ~ ~ ~ detect ~-1 ~-1 ~-1 minecraft:cherry_log 0 function egg/cherry

execute @e[type=dragonmountsplus:forest_dragon_egg,scores={Timer=6000}] ~~~ detect ~ ~-1 ~ minecraft:cherry_leaves 8 execute @s ~ ~ ~ detect ~1 ~-1 ~ minecraft:cherry_leaves 8 execute @s ~ ~ ~ detect ~-1 ~-1 ~ minecraft:cherry_leaves 8 execute @s ~ ~ ~ detect ~ ~-1 ~1 minecraft:cherry_leaves 8 execute @s ~ ~ ~ detect ~ ~-1 ~-1 minecraft:cherry_leaves 8 execute @s ~ ~ ~ detect ~1 ~-1 ~1 minecraft:cherry_leaves 8 execute @s ~ ~ ~ detect ~-1 ~-1 ~1 minecraft:cherry_leaves 8 execute @s ~ ~ ~ detect ~1 ~-1 ~-1 minecraft:cherry_leaves 8 execute @s ~ ~ ~ detect ~-1 ~-1 ~-1 minecraft:cherry_leaves 8 function egg/cherry

execute @e[type=dragonmountsplus:forest_dragon_egg,scores={Timer=6000}] ~~~ detect ~ ~-1 ~ minecraft:cherry_leaves 4 execute @s ~ ~ ~ detect ~1 ~-1 ~ minecraft:cherry_leaves 4 execute @s ~ ~ ~ detect ~-1 ~-1 ~ minecraft:cherry_leaves 4 execute @s ~ ~ ~ detect ~ ~-1 ~1 minecraft:cherry_leaves 4 execute @s ~ ~ ~ detect ~ ~-1 ~-1 minecraft:cherry_leaves 4 execute @s ~ ~ ~ detect ~1 ~-1 ~1 minecraft:cherry_leaves 4 execute @s ~ ~ ~ detect ~-1 ~-1 ~1 minecraft:cherry_leaves 4 execute @s ~ ~ ~ detect ~1 ~-1 ~-1 minecraft:cherry_leaves 4 execute @s ~ ~ ~ detect ~-1 ~-1 ~-1 minecraft:cherry_leaves 4 function egg/cherry

execute @e[type=dragonmountsplus:forest_dragon_egg,scores={Timer=6000}] ~~~ detect ~ ~-1 ~ minecraft:cherry_leaves 0 execute @s ~ ~ ~ detect ~1 ~-1 ~ minecraft:cherry_leaves 0 execute @s ~ ~ ~ detect ~-1 ~-1 ~ minecraft:cherry_leaves 0 execute @s ~ ~ ~ detect ~ ~-1 ~1 minecraft:cherry_leaves 0 execute @s ~ ~ ~ detect ~ ~-1 ~-1 minecraft:cherry_leaves 0 execute @s ~ ~ ~ detect ~1 ~-1 ~1 minecraft:cherry_leaves 0 execute @s ~ ~ ~ detect ~-1 ~-1 ~1 minecraft:cherry_leaves 0 execute @s ~ ~ ~ detect ~1 ~-1 ~-1 minecraft:cherry_leaves 0 execute @s ~ ~ ~ detect ~-1 ~-1 ~-1 minecraft:cherry_leaves 0 function egg/cherry

execute @e[type=dragonmountsplus:ender_dragon_egg,scores={Timer=6000}] ~~~ detect ~ ~-1 ~ minecraft:cherry_log 0 execute @s ~ ~ ~ detect ~1 ~-1 ~ minecraft:cherry_log 0 execute @s ~ ~ ~ detect ~-1 ~-1 ~ minecraft:cherry_log 0 execute @s ~ ~ ~ detect ~ ~-1 ~1 minecraft:cherry_log 0 execute @s ~ ~ ~ detect ~ ~-1 ~-1 minecraft:cherry_log 0 execute @s ~ ~ ~ detect ~1 ~-1 ~1 minecraft:cherry_log 0 execute @s ~ ~ ~ detect ~-1 ~-1 ~1 minecraft:cherry_log 0 execute @s ~ ~ ~ detect ~1 ~-1 ~-1 minecraft:cherry_log 0 execute @s ~ ~ ~ detect ~-1 ~-1 ~-1 minecraft:cherry_log 0 function egg/cherry

execute @e[type=dragonmountsplus:ender_dragon_egg,scores={Timer=6000}] ~~~ detect ~ ~-1 ~ minecraft:cherry_leaves 8 execute @s ~ ~ ~ detect ~1 ~-1 ~ minecraft:cherry_leaves 8 execute @s ~ ~ ~ detect ~-1 ~-1 ~ minecraft:cherry_leaves 8 execute @s ~ ~ ~ detect ~ ~-1 ~1 minecraft:cherry_leaves 8 execute @s ~ ~ ~ detect ~ ~-1 ~-1 minecraft:cherry_leaves 8 execute @s ~ ~ ~ detect ~1 ~-1 ~1 minecraft:cherry_leaves 8 execute @s ~ ~ ~ detect ~-1 ~-1 ~1 minecraft:cherry_leaves 8 execute @s ~ ~ ~ detect ~1 ~-1 ~-1 minecraft:cherry_leaves 8 execute @s ~ ~ ~ detect ~-1 ~-1 ~-1 minecraft:cherry_leaves 8 function egg/cherry

execute @e[type=dragonmountsplus:ender_dragon_egg,scores={Timer=6000}] ~~~ detect ~ ~-1 ~ minecraft:cherry_leaves 4 execute @s ~ ~ ~ detect ~1 ~-1 ~ minecraft:cherry_leaves 4 execute @s ~ ~ ~ detect ~-1 ~-1 ~ minecraft:cherry_leaves 4 execute @s ~ ~ ~ detect ~ ~-1 ~1 minecraft:cherry_leaves 4 execute @s ~ ~ ~ detect ~ ~-1 ~-1 minecraft:cherry_leaves 4 execute @s ~ ~ ~ detect ~1 ~-1 ~1 minecraft:cherry_leaves 4 execute @s ~ ~ ~ detect ~-1 ~-1 ~1 minecraft:cherry_leaves 4 execute @s ~ ~ ~ detect ~1 ~-1 ~-1 minecraft:cherry_leaves 4 execute @s ~ ~ ~ detect ~-1 ~-1 ~-1 minecraft:cherry_leaves 4 function egg/cherry

execute @e[type=dragonmountsplus:ender_dragon_egg,scores={Timer=6000}] ~~~ detect ~ ~-1 ~ minecraft:cherry_leaves 0 execute @s ~ ~ ~ detect ~1 ~-1 ~ minecraft:cherry_leaves 0 execute @s ~ ~ ~ detect ~-1 ~-1 ~ minecraft:cherry_leaves 0 execute @s ~ ~ ~ detect ~ ~-1 ~1 minecraft:cherry_leaves 0 execute @s ~ ~ ~ detect ~ ~-1 ~-1 minecraft:cherry_leaves 0 execute @s ~ ~ ~ detect ~1 ~-1 ~1 minecraft:cherry_leaves 0 execute @s ~ ~ ~ detect ~-1 ~-1 ~1 minecraft:cherry_leaves 0 execute @s ~ ~ ~ detect ~1 ~-1 ~-1 minecraft:cherry_leaves 0 execute @s ~ ~ ~ detect ~-1 ~-1 ~-1 minecraft:cherry_leaves 0 function egg/cherry

execute @e[type=dragonmountsplus:ender_dragon_egg,scores={Timer=6000}] ~~~ detect ~ ~-1 ~ minecraft:cherry_leaves 12 execute @s ~ ~ ~ detect ~1 ~-1 ~ minecraft:cherry_leaves 12 execute @s ~ ~ ~ detect ~-1 ~-1 ~ minecraft:cherry_leaves 12 execute @s ~ ~ ~ detect ~ ~-1 ~1 minecraft:cherry_leaves 12 execute @s ~ ~ ~ detect ~ ~-1 ~-1 minecraft:cherry_leaves 12 execute @s ~ ~ ~ detect ~1 ~-1 ~1 minecraft:cherry_leaves 12 execute @s ~ ~ ~ detect ~-1 ~-1 ~1 minecraft:cherry_leaves 12 execute @s ~ ~ ~ detect ~1 ~-1 ~-1 minecraft:cherry_leaves 12 execute @s ~ ~ ~ detect ~-1 ~-1 ~-1 minecraft:cherry_leaves 12 function egg/cherry

execute @e[type=dragonmountsplus:forest_dragon_egg,scores={Timer=6000}] ~~~ detect ~ ~-1 ~ minecraft:cherry_leaves 12 execute @s ~ ~ ~ detect ~1 ~-1 ~ minecraft:cherry_leaves 12 execute @s ~ ~ ~ detect ~-1 ~-1 ~ minecraft:cherry_leaves 12 execute @s ~ ~ ~ detect ~ ~-1 ~1 minecraft:cherry_leaves 12 execute @s ~ ~ ~ detect ~ ~-1 ~-1 minecraft:cherry_leaves 12 execute @s ~ ~ ~ detect ~1 ~-1 ~1 minecraft:cherry_leaves 12 execute @s ~ ~ ~ detect ~-1 ~-1 ~1 minecraft:cherry_leaves 12 execute @s ~ ~ ~ detect ~1 ~-1 ~-1 minecraft:cherry_leaves 12 execute @s ~ ~ ~ detect ~-1 ~-1 ~-1 minecraft:cherry_leaves 12 function egg/cherry

execute @e[type=dragonmountsplus:cherry_dragon_egg,scores={Timer=6000}] ~~~ detect ~1 ~-1 ~ minecraft:lava 0 execute @s ~ ~ ~ detect ~-1 ~-1 ~ minecraft:lava 0 execute @s ~ ~ ~ detect ~ ~-1 ~1 minecraft:lava 0 execute @s ~ ~ ~ detect ~ ~-1 ~-1 minecraft:lava 0 execute @s ~ ~ ~ detect ~1 ~-1 ~1 minecraft:lava 0 execute @s ~ ~ ~ detect ~-1 ~-1 ~1 minecraft:lava 0 execute @s ~ ~ ~ detect ~1 ~-1 ~-1 minecraft:lava 0 execute @s ~ ~ ~ detect ~-1 ~-1 ~-1 minecraft:lava 0 function egg/fire

execute @e[type=dragonmountsplus:cherry_dragon_egg,scores={Timer=6000}] ~~~ detect ~ ~-1 ~ minecraft:oak_log 0 execute @s ~ ~ ~ detect ~1 ~-1 ~ minecraft:oak_log 0 execute @s ~ ~ ~ detect ~-1 ~-1 ~ minecraft:oak_log 0 execute @s ~ ~ ~ detect ~ ~-1 ~1 minecraft:oak_log 0 execute @s ~ ~ ~ detect ~ ~-1 ~-1 minecraft:oak_log 0 execute @s ~ ~ ~ detect ~1 ~-1 ~1 minecraft:oak_log 0 execute @s ~ ~ ~ detect ~-1 ~-1 ~1 minecraft:oak_log 0 execute @s ~ ~ ~ detect ~1 ~-1 ~-1 minecraft:oak_log 0 execute @s ~ ~ ~ detect ~-1 ~-1 ~-1 minecraft:oak_log 0 function egg/forest

execute @e[type=dragonmountsplus:cherry_dragon_egg,scores={Timer=6000}] ~~~ detect  ~1 ~-1 ~ minecraft:water 0 execute @s ~ ~ ~ detect ~-1 ~-1 ~ minecraft:water 0 execute @s ~ ~ ~ detect ~ ~-1 ~1 minecraft:water 0 execute @s ~ ~ ~ detect ~ ~-1 ~-1 minecraft:water 0 execute @s ~ ~ ~ detect ~1 ~-1 ~1 minecraft:water 0 execute @s ~ ~ ~ detect ~-1 ~-1 ~1 minecraft:water 0 execute @s ~ ~ ~ detect ~1 ~-1 ~-1 minecraft:water 0 execute @s ~ ~ ~ detect ~-1 ~-1 ~-1 minecraft:water 0 function egg/water

execute @e[type=dragonmountsplus:cherry_dragon_egg,scores={Timer=6000}] ~~~ detect ~ ~-1 ~ minecraft:oak_leaves 12 execute @s ~ ~ ~ detect ~1 ~-1 ~ minecraft:oak_leaves 12 execute @s ~ ~ ~ detect ~-1 ~-1 ~ minecraft:oak_leaves 12 execute @s ~ ~ ~ detect ~ ~-1 ~1 minecraft:oak_leaves 12 execute @s ~ ~ ~ detect ~ ~-1 ~-1 minecraft:oak_leaves 12 execute @s ~ ~ ~ detect ~1 ~-1 ~1 minecraft:oak_leaves 12 execute @s ~ ~ ~ detect ~-1 ~-1 ~1 minecraft:oak_leaves 12 execute @s ~ ~ ~ detect ~1 ~-1 ~-1 minecraft:oak_leaves 12 execute @s ~ ~ ~ detect ~-1 ~-1 ~-1 minecraft:oak_leaves 12 function egg/forest

execute @e[type=dragonmountsplus:cherry_dragon_egg,scores={Timer=6000}] ~~~ detect ~ ~-1 ~ minecraft:snow 0  execute @s ~ ~ ~ detect ~1 ~-1 ~ minecraft:snow 0 execute @s ~ ~ ~ detect ~-1 ~-1 ~ minecraft:snow 0 execute @s ~ ~ ~ detect ~ ~-1 ~1 minecraft:snow 0 execute @s ~ ~ ~ detect ~ ~-1 ~-1 minecraft:snow 0 execute @s ~ ~ ~ detect ~1 ~-1 ~1 minecraft:snow 0 execute @s ~ ~ ~ detect ~-1 ~-1 ~1 minecraft:snow 0 execute @s ~ ~ ~ detect ~1 ~-1 ~-1 minecraft:snow 0 execute @s ~ ~ ~ detect ~-1 ~-1 ~-1 minecraft:snow 0 function egg/ice

execute @e[type=dragonmountsplus:cherry_dragon_egg,scores={Timer=6000}] ~~~ detect ~ ~-1 ~ minecraft:oak_log 0 execute @s ~ ~ ~ detect ~1 ~-1 ~ minecraft:oak_log 0 execute @s ~ ~ ~ detect ~-1 ~-1 ~ minecraft:oak_log 0 execute @s ~ ~ ~ detect ~ ~-1 ~1 minecraft:oak_log 0 execute @s ~ ~ ~ detect ~ ~-1 ~-1 minecraft:oak_log 0 execute @s ~ ~ ~ detect ~1 ~-1 ~1 minecraft:oak_log 0 execute @s ~ ~ ~ detect ~-1 ~-1 ~1 minecraft:oak_log 0 execute @s ~ ~ ~ detect ~1 ~-1 ~-1 minecraft:oak_log 0 execute @s ~ ~ ~ detect ~-1 ~-1 ~-1 minecraft:oak_log 0 function egg/forest

execute @e[type=dragonmountsplus:cherry_dragon_egg,scores={Timer=6000}] ~~~ detect ~~~ minecraft:daylight_detector_inverted 0 function egg/moonlight
execute @e[type=dragonmountsplus:cherry_dragon_egg,scores={Timer=6000}] ~~~ detect ~~~ minecraft:daylight_detector_inverted 1 function egg/moonlight
execute @e[type=dragonmountsplus:cherry_dragon_egg,scores={Timer=6000}] ~~~ detect ~~~ minecraft:daylight_detector_inverted 2 function egg/moonlight
execute @e[type=dragonmountsplus:cherry_dragon_egg,scores={Timer=6000}] ~~~ detect ~~~ minecraft:daylight_detector_inverted 3 function egg/moonlight
execute @e[type=dragonmountsplus:cherry_dragon_egg,scores={Timer=6000}] ~~~ detect ~~~ minecraft:daylight_detector_inverted 4 function egg/moonlight
execute @e[type=dragonmountsplus:cherry_dragon_egg,scores={Timer=6000}] ~~~ detect ~~~ minecraft:daylight_detector_inverted 5 function egg/moonlight
execute @e[type=dragonmountsplus:cherry_dragon_egg,scores={Timer=6000}] ~~~ detect ~~~ minecraft:daylight_detector_inverted 6 function egg/moonlight
execute @e[type=dragonmountsplus:cherry_dragon_egg,scores={Timer=6000}] ~~~ detect ~~~ minecraft:daylight_detector_inverted 7 function egg/moonlight
execute @e[type=dragonmountsplus:cherry_dragon_egg,scores={Timer=6000}] ~~~ detect ~~~ minecraft:daylight_detector_inverted 8 function egg/moonlight
execute @e[type=dragonmountsplus:cherry_dragon_egg,scores={Timer=6000}] ~~~ detect ~~~ minecraft:daylight_detector_inverted 9 function egg/moonlight
execute @e[type=dragonmountsplus:cherry_dragon_egg,scores={Timer=6000}] ~~~ detect ~~~ minecraft:daylight_detector_inverted 10 function egg/moonlight
execute @e[type=dragonmountsplus:cherry_dragon_egg,scores={Timer=6000}] ~~~ detect ~~~ minecraft:daylight_detector_inverted 11 function egg/moonlight
execute @e[type=dragonmountsplus:cherry_dragon_egg,scores={Timer=6000}] ~~~ detect ~~~ minecraft:daylight_detector_inverted 12 function egg/moonlight
execute @e[type=dragonmountsplus:water_dragon_egg,scores={Timer=6000}] ~~~ detect ~~~ minecraft:daylight_detector_inverted 13 function egg/moonlight
execute @e[type=dragonmountsplus:cherry_dragon_egg,scores={Timer=6000}] ~~~ detect ~~~ minecraft:daylight_detector_inverted 14 function egg/moonlight
execute @e[type=dragonmountsplus:cherry_dragon_egg,scores={Timer=6000}] ~~~ detect ~~~ minecraft:daylight_detector_inverted 15 function egg/moonlight

execute @e[type=dragonmountsplus:cherry_dragon_egg,scores={Timer=6000}] ~~~ detect ~ ~-1 ~ minecraft:hardened_clay 0  execute @s ~ ~ ~ detect ~1 ~-1 ~ minecraft:hardened_clay 0 execute @s ~ ~ ~ detect ~-1 ~-1 ~ minecraft:hardened_clay 0 execute @s ~ ~ ~ detect ~ ~-1 ~1 minecraft:hardened_clay 0 execute @s ~ ~ ~ detect ~ ~-1 ~-1 minecraft:hardened_clay 0 execute @s ~ ~ ~ detect ~1 ~-1 ~1 minecraft:hardened_clay 0 execute @s ~ ~ ~ detect ~-1 ~-1 ~1 minecraft:hardened_clay 0 execute @s ~ ~ ~ detect ~1 ~-1 ~-1 minecraft:hardened_clay 0 execute @s ~ ~ ~ detect ~-1 ~-1 ~-1 minecraft:hardened_clay 0 function egg/terra

execute @e[type=dragonmountsplus:cherry_dragon_egg,scores={Timer=6000}] ~~~ detect ~ ~-1 ~ minecraft:bone_block 0 execute @s ~ ~ ~ detect ~1 ~-1 ~ minecraft:bone_block 0 execute @s ~ ~ ~ detect ~-1 ~-1 ~ minecraft:bone_block 0 execute @s ~ ~ ~ detect ~ ~-1 ~1 minecraft:bone_block 0 execute @s ~ ~ ~ detect ~ ~-1 ~-1 minecraft:bone_block 0 execute @s ~ ~ ~ detect ~1 ~-1 ~1 minecraft:bone_block 0 execute @s ~ ~ ~ detect ~-1 ~-1 ~1 minecraft:bone_block 0 execute @s ~ ~ ~ detect ~1 ~-1 ~-1 minecraft:bone_block 0 execute @s ~ ~ ~ detect ~-1 ~-1 ~-1 minecraft:bone_block 0 function egg/skeleton

execute @e[type=dragonmountsplus:cherry_dragon_egg,scores={Timer=6000}] ~~~ detect ~ ~-1 ~ minecraft:mossy_cobblestone 0  execute @s ~ ~ ~ detect ~1 ~-1 ~ minecraft:mossy_cobblestone 0 execute @s ~ ~ ~ detect ~-1 ~-1 ~ minecraft:mossy_cobblestone 0 execute @s ~ ~ ~ detect ~ ~-1 ~1 minecraft:mossy_cobblestone 0 execute @s ~ ~ ~ detect ~ ~-1 ~-1 minecraft:mossy_cobblestone 0 execute @s ~ ~ ~ detect ~1 ~-1 ~1 minecraft:mossy_cobblestone 0 execute @s ~ ~ ~ detect ~-1 ~-1 ~1 minecraft:mossy_cobblestone 0 execute @s ~ ~ ~ detect ~1 ~-1 ~-1 minecraft:mossy_cobblestone 0 execute @s ~ ~ ~ detect ~-1 ~-1 ~-1 minecraft:mossy_cobblestone 0 function egg/zombie

execute @e[type=dragonmountsplus:cherry_dragon_egg,scores={Timer=6000}] ~~~ detect ~ ~-1 ~ minecraft:ice 0 execute @s ~ ~ ~ detect ~1 ~-1 ~ minecraft:ice 0 execute @s ~ ~ ~ detect ~-1 ~-1 ~ minecraft:ice 0 execute @s ~ ~ ~ detect ~ ~-1 ~1 minecraft:ice 0 execute @s ~ ~ ~ detect ~ ~-1 ~-1 minecraft:ice 0 execute @s ~ ~ ~ detect ~1 ~-1 ~1 minecraft:ice 0 execute @s ~ ~ ~ detect ~-1 ~-1 ~1 minecraft:ice 0 execute @s ~ ~ ~ detect ~1 ~-1 ~-1 minecraft:ice 0 execute @s ~ ~ ~ detect ~-1 ~-1 ~-1 minecraft:ice 0 function egg/ice

execute @e[type=dragonmountsplus:cherry_dragon_egg,scores={Timer=6000}] ~~~ detect ~ ~-1 ~ minecraft:blue_ice 0  execute @s ~ ~ ~ detect ~1 ~-1 ~ minecraft:blue_ice 0 execute @s ~ ~ ~ detect ~-1 ~-1 ~ minecraft:blue_ice 0 execute @s ~ ~ ~ detect ~ ~-1 ~1 minecraft:blue_ice 0 execute @s ~ ~ ~ detect ~ ~-1 ~-1 minecraft:blue_ice 0 execute @s ~ ~ ~ detect ~1 ~-1 ~1 minecraft:blue_ice 0 execute @s ~ ~ ~ detect ~-1 ~-1 ~1 minecraft:blue_ice 0 execute @s ~ ~ ~ detect ~1 ~-1 ~-1 minecraft:blue_ice 0 execute @s ~ ~ ~ detect ~-1 ~-1 ~-1 minecraft:blue_ice 0 function egg/ice

execute @e[type=dragonmountsplus:cherry_dragon_egg,scores={Timer=6000}] ~~~ detect ~ ~-1 ~ minecraft:packed_ice 0  execute @s ~ ~ ~ detect ~1 ~-1 ~ minecraft:packed_ice 0 execute @s ~ ~ ~ detect ~-1 ~-1 ~ minecraft:packed_ice 0 execute @s ~ ~ ~ detect ~ ~-1 ~1 minecraft:packed_ice 0 execute @s ~ ~ ~ detect ~ ~-1 ~-1 minecraft:packed_ice 0 execute @s ~ ~ ~ detect ~1 ~-1 ~1 minecraft:packed_ice 0 execute @s ~ ~ ~ detect ~-1 ~-1 ~1 minecraft:packed_ice 0 execute @s ~ ~ ~ detect ~1 ~-1 ~-1 minecraft:packed_ice 0 execute @s ~ ~ ~ detect ~-1 ~-1 ~-1 minecraft:packed_ice 0 function egg/ice

execute @e[type=dragonmountsplus:cherry_dragon_egg,scores={Timer=6000}] ~~~ detect ~ ~-1 ~ minecraft:sand 0 execute @s ~ ~ ~ detect ~1 ~-1 ~ minecraft:sand 0 execute @s ~ ~ ~ detect ~-1 ~-1 ~ minecraft:sand 0 execute @s ~ ~ ~ detect ~ ~-1 ~1 minecraft:sand 0 execute @s ~ ~ ~ detect ~ ~-1 ~-1 minecraft:sand 0 execute @s ~ ~ ~ detect ~1 ~-1 ~1 minecraft:sand 0 execute @s ~ ~ ~ detect ~-1 ~-1 ~1 minecraft:sand 0 execute @s ~ ~ ~ detect ~1 ~-1 ~-1 minecraft:sand 0 execute @s ~ ~ ~ detect ~-1 ~-1 ~-1 minecraft:sand 0 function egg/terra

execute @e[type=dragonmountsplus:cherry_dragon_egg,scores={Timer=6000}] ~~~ detect ~ ~-1 ~ minecraft:red_sand 0  execute @s ~ ~ ~ detect ~1 ~-1 ~ minecraft:red_sand 0 execute @s ~ ~ ~ detect ~-1 ~-1 ~ minecraft:red_sand 0 execute @s ~ ~ ~ detect ~ ~-1 ~1 minecraft:red_sand 0 execute @s ~ ~ ~ detect ~ ~-1 ~-1 minecraft:red_sand 0 execute @s ~ ~ ~ detect ~1 ~-1 ~1 minecraft:red_sand 0 execute @s ~ ~ ~ detect ~-1 ~-1 ~1 minecraft:red_sand 0 execute @s ~ ~ ~ detect ~1 ~-1 ~-1 minecraft:red_sand 0 execute @s ~ ~ ~ detect ~-1 ~-1 ~-1 minecraft:red_sand 0 function egg/terra

execute @e[type=dragonmountsplus:cherry_dragon_egg,scores={Timer=6000}] ~~~ detect ~ ~-1 ~ minecraft:oak_leaves 8 execute @s ~ ~ ~ detect ~1 ~-1 ~ minecraft:oak_leaves 8 execute @s ~ ~ ~ detect ~-1 ~-1 ~ minecraft:oak_leaves 8 execute @s ~ ~ ~ detect ~ ~-1 ~1 minecraft:oak_leaves 8 execute @s ~ ~ ~ detect ~ ~-1 ~-1 minecraft:oak_leaves 8 execute @s ~ ~ ~ detect ~1 ~-1 ~1 minecraft:oak_leaves 8 execute @s ~ ~ ~ detect ~-1 ~-1 ~1 minecraft:oak_leaves 8 execute @s ~ ~ ~ detect ~1 ~-1 ~-1 minecraft:oak_leaves 8 execute @s ~ ~ ~ detect ~-1 ~-1 ~-1 minecraft:oak_leaves 8 function egg/forest

execute @e[type=dragonmountsplus:cherry_dragon_egg,scores={Timer=6000}] ~~~ detect ~ ~-1 ~ minecraft:oak_leaves 4 execute @s ~ ~ ~ detect ~1 ~-1 ~ minecraft:oak_leaves 4 execute @s ~ ~ ~ detect ~-1 ~-1 ~ minecraft:oak_leaves 4 execute @s ~ ~ ~ detect ~ ~-1 ~1 minecraft:oak_leaves 4 execute @s ~ ~ ~ detect ~ ~-1 ~-1 minecraft:oak_leaves 4 execute @s ~ ~ ~ detect ~1 ~-1 ~1 minecraft:oak_leaves 4 execute @s ~ ~ ~ detect ~-1 ~-1 ~1 minecraft:oak_leaves 4 execute @s ~ ~ ~ detect ~1 ~-1 ~-1 minecraft:oak_leaves 4 execute @s ~ ~ ~ detect ~-1 ~-1 ~-1 minecraft:oak_leaves 4 function egg/forest

execute @e[type=dragonmountsplus:cherry_dragon_egg,scores={Timer=6000}] ~~~ detect ~ ~-1 ~ minecraft:oak_leaves 0 execute @s ~ ~ ~ detect ~1 ~-1 ~ minecraft:oak_leaves 0 execute @s ~ ~ ~ detect ~-1 ~-1 ~ minecraft:oak_leaves 0 execute @s ~ ~ ~ detect ~ ~-1 ~1 minecraft:oak_leaves 0 execute @s ~ ~ ~ detect ~ ~-1 ~-1 minecraft:oak_leaves 0 execute @s ~ ~ ~ detect ~1 ~-1 ~1 minecraft:oak_leaves 0 execute @s ~ ~ ~ detect ~-1 ~-1 ~1 minecraft:oak_leaves 0 execute @s ~ ~ ~ detect ~1 ~-1 ~-1 minecraft:oak_leaves 0 execute @s ~ ~ ~ detect ~-1 ~-1 ~-1 minecraft:oak_leaves 0 function egg/forest

execute @e[type=dragonmountsplus:cherry_dragon_egg,scores={Timer=6000}] ~~~ detect ~~~ minecraft:daylight_detector 0 function egg/sunlight
execute @e[type=dragonmountsplus:cherry_dragon_egg,scores={Timer=6000}] ~~~ detect ~~~ minecraft:daylight_detector 1 function egg/sunlight
execute @e[type=dragonmountsplus:cherry_dragon_egg,scores={Timer=6000}] ~~~ detect ~~~ minecraft:daylight_detector 2 function egg/sunlight
execute @e[type=dragonmountsplus:cherry_dragon_egg,scores={Timer=6000}] ~~~ detect ~~~ minecraft:daylight_detector 3 function egg/sunlight
execute @e[type=dragonmountsplus:cherry_dragon_egg,scores={Timer=6000}] ~~~ detect ~~~ minecraft:daylight_detector 4 function egg/sunlight
execute @e[type=dragonmountsplus:cherry_dragon_egg,scores={Timer=6000}] ~~~ detect ~~~ minecraft:daylight_detector 5 function egg/sunlight
execute @e[type=dragonmountsplus:cherry_dragon_egg,scores={Timer=6000}] ~~~ detect ~~~ minecraft:daylight_detector 6 function egg/sunlight
execute @e[type=dragonmountsplus:cherry_dragon_egg,scores={Timer=6000}] ~~~ detect ~~~ minecraft:daylight_detector 7 function egg/sunlight
execute @e[type=dragonmountsplus:cherry_dragon_egg,scores={Timer=6000}] ~~~ detect ~~~ minecraft:daylight_detector 8 function egg/sunlight
execute @e[type=dragonmountsplus:cherry_dragon_egg,scores={Timer=6000}] ~~~ detect ~~~ minecraft:daylight_detector 9 function egg/sunlight
execute @e[type=dragonmountsplus:cherry_dragon_egg,scores={Timer=6000}] ~~~ detect ~~~ minecraft:daylight_detector 10 function egg/sunlight
execute @e[type=dragonmountsplus:cherry_dragon_egg,scores={Timer=6000}] ~~~ detect ~~~ minecraft:daylight_detector 11 function egg/sunlight
execute @e[type=dragonmountsplus:cherry_dragon_egg,scores={Timer=6000}] ~~~ detect ~~~ minecraft:daylight_detector 12 function egg/sunlight
execute @e[type=dragonmountsplus:water_dragon_egg,scores={Timer=6000}] ~~~ detect ~~~ minecraft:daylight_detector 13 function egg/sunlight
execute @e[type=dragonmountsplus:cherry_dragon_egg,scores={Timer=6000}] ~~~ detect ~~~ minecraft:daylight_detector 14 function egg/sunlight
execute @e[type=dragonmountsplus:cherry_dragon_egg,scores={Timer=6000}] ~~~ detect ~~~ minecraft:daylight_detector 15 function egg/sunlight

execute @e[type=dragonmountsplus:skeleton_dragon_egg,scores={Timer=6000}] ~~~ detect ~1 ~-1 ~ minecraft:emerald_block 0 execute @s ~ ~ ~ detect ~-1 ~-1 ~ minecraft:emerald_block 0 execute @s ~ ~ ~ detect ~ ~-1 ~1 minecraft:emerald_block 0 execute @s ~ ~ ~ detect ~ ~-1 ~-1 minecraft:emerald_block 0 execute @s ~ ~ ~ detect ~1 ~-1 ~1 minecraft:emerald_block 0 execute @s ~ ~ ~ detect ~-1 ~-1 ~1 minecraft:emerald_block 0 execute @s ~ ~ ~ detect ~1 ~-1 ~-1 minecraft:emerald_block 0 execute @s ~ ~ ~ detect ~-1 ~-1 ~-1 minecraft:emerald_block 0 function egg/phantom

execute @e[type=dragonmountsplus:ender_dragon_egg,scores={Timer=6000}] ~~~ detect ~1 ~-1 ~ minecraft:emerald_block 0 execute @s ~ ~ ~ detect ~-1 ~-1 ~ minecraft:emerald_block 0 execute @s ~ ~ ~ detect ~ ~-1 ~1 minecraft:emerald_block 0 execute @s ~ ~ ~ detect ~ ~-1 ~-1 minecraft:emerald_block 0 execute @s ~ ~ ~ detect ~1 ~-1 ~1 minecraft:emerald_block 0 execute @s ~ ~ ~ detect ~-1 ~-1 ~1 minecraft:emerald_block 0 execute @s ~ ~ ~ detect ~1 ~-1 ~-1 minecraft:emerald_block 0 execute @s ~ ~ ~ detect ~-1 ~-1 ~-1 minecraft:emerald_block 0 function egg/phantom

execute @e[type=dragonmountsplus:phantom_dragon_egg,scores={Timer=6000}] ~~~ detect ~1 ~-1 ~ minecraft:lava 0 execute @s ~ ~ ~ detect ~-1 ~-1 ~ minecraft:lava 0 execute @s ~ ~ ~ detect ~ ~-1 ~1 minecraft:lava 0 execute @s ~ ~ ~ detect ~ ~-1 ~-1 minecraft:lava 0 execute @s ~ ~ ~ detect ~1 ~-1 ~1 minecraft:lava 0 execute @s ~ ~ ~ detect ~-1 ~-1 ~1 minecraft:lava 0 execute @s ~ ~ ~ detect ~1 ~-1 ~-1 minecraft:lava 0 execute @s ~ ~ ~ detect ~-1 ~-1 ~-1 minecraft:lava 0 function egg/fire

execute @e[type=dragonmountsplus:phantom_dragon_egg,scores={Timer=6000}] ~~~ detect ~ ~-1 ~ minecraft:oak_log 0 execute @s ~ ~ ~ detect ~1 ~-1 ~ minecraft:oak_log 0 execute @s ~ ~ ~ detect ~-1 ~-1 ~ minecraft:oak_log 0 execute @s ~ ~ ~ detect ~ ~-1 ~1 minecraft:oak_log 0 execute @s ~ ~ ~ detect ~ ~-1 ~-1 minecraft:oak_log 0 execute @s ~ ~ ~ detect ~1 ~-1 ~1 minecraft:oak_log 0 execute @s ~ ~ ~ detect ~-1 ~-1 ~1 minecraft:oak_log 0 execute @s ~ ~ ~ detect ~1 ~-1 ~-1 minecraft:oak_log 0 execute @s ~ ~ ~ detect ~-1 ~-1 ~-1 minecraft:oak_log 0 function egg/forest

execute @e[type=dragonmountsplus:phantom_dragon_egg,scores={Timer=6000}] ~~~ detect  ~1 ~-1 ~ minecraft:water 0 execute @s ~ ~ ~ detect ~-1 ~-1 ~ minecraft:water 0 execute @s ~ ~ ~ detect ~ ~-1 ~1 minecraft:water 0 execute @s ~ ~ ~ detect ~ ~-1 ~-1 minecraft:water 0 execute @s ~ ~ ~ detect ~1 ~-1 ~1 minecraft:water 0 execute @s ~ ~ ~ detect ~-1 ~-1 ~1 minecraft:water 0 execute @s ~ ~ ~ detect ~1 ~-1 ~-1 minecraft:water 0 execute @s ~ ~ ~ detect ~-1 ~-1 ~-1 minecraft:water 0 function egg/water

execute @e[type=dragonmountsplus:phantom_dragon_egg,scores={Timer=6000}] ~~~ detect ~ ~-1 ~ minecraft:oak_leaves 12 execute @s ~ ~ ~ detect ~1 ~-1 ~ minecraft:oak_leaves 12 execute @s ~ ~ ~ detect ~-1 ~-1 ~ minecraft:oak_leaves 12 execute @s ~ ~ ~ detect ~ ~-1 ~1 minecraft:oak_leaves 12 execute @s ~ ~ ~ detect ~ ~-1 ~-1 minecraft:oak_leaves 12 execute @s ~ ~ ~ detect ~1 ~-1 ~1 minecraft:oak_leaves 12 execute @s ~ ~ ~ detect ~-1 ~-1 ~1 minecraft:oak_leaves 12 execute @s ~ ~ ~ detect ~1 ~-1 ~-1 minecraft:oak_leaves 12 execute @s ~ ~ ~ detect ~-1 ~-1 ~-1 minecraft:oak_leaves 12 function egg/forest

execute @e[type=dragonmountsplus:phantom_dragon_egg,scores={Timer=6000}] ~~~ detect ~ ~-1 ~ minecraft:snow 0  execute @s ~ ~ ~ detect ~1 ~-1 ~ minecraft:snow 0 execute @s ~ ~ ~ detect ~-1 ~-1 ~ minecraft:snow 0 execute @s ~ ~ ~ detect ~ ~-1 ~1 minecraft:snow 0 execute @s ~ ~ ~ detect ~ ~-1 ~-1 minecraft:snow 0 execute @s ~ ~ ~ detect ~1 ~-1 ~1 minecraft:snow 0 execute @s ~ ~ ~ detect ~-1 ~-1 ~1 minecraft:snow 0 execute @s ~ ~ ~ detect ~1 ~-1 ~-1 minecraft:snow 0 execute @s ~ ~ ~ detect ~-1 ~-1 ~-1 minecraft:snow 0 function egg/ice

execute @e[type=dragonmountsplus:phantom_dragon_egg,scores={Timer=6000}] ~~~ detect ~ ~-1 ~ minecraft:oak_log 0 execute @s ~ ~ ~ detect ~1 ~-1 ~ minecraft:oak_log 0 execute @s ~ ~ ~ detect ~-1 ~-1 ~ minecraft:oak_log 0 execute @s ~ ~ ~ detect ~ ~-1 ~1 minecraft:oak_log 0 execute @s ~ ~ ~ detect ~ ~-1 ~-1 minecraft:oak_log 0 execute @s ~ ~ ~ detect ~1 ~-1 ~1 minecraft:oak_log 0 execute @s ~ ~ ~ detect ~-1 ~-1 ~1 minecraft:oak_log 0 execute @s ~ ~ ~ detect ~1 ~-1 ~-1 minecraft:oak_log 0 execute @s ~ ~ ~ detect ~-1 ~-1 ~-1 minecraft:oak_log 0 function egg/forest

execute @e[type=dragonmountsplus:phantom_dragon_egg,scores={Timer=6000}] ~~~ detect ~~~ minecraft:daylight_detector_inverted 0 function egg/moonlight
execute @e[type=dragonmountsplus:phantom_dragon_egg,scores={Timer=6000}] ~~~ detect ~~~ minecraft:daylight_detector_inverted 1 function egg/moonlight
execute @e[type=dragonmountsplus:phantom_dragon_egg,scores={Timer=6000}] ~~~ detect ~~~ minecraft:daylight_detector_inverted 2 function egg/moonlight
execute @e[type=dragonmountsplus:phantom_dragon_egg,scores={Timer=6000}] ~~~ detect ~~~ minecraft:daylight_detector_inverted 3 function egg/moonlight
execute @e[type=dragonmountsplus:phantom_dragon_egg,scores={Timer=6000}] ~~~ detect ~~~ minecraft:daylight_detector_inverted 4 function egg/moonlight
execute @e[type=dragonmountsplus:phantom_dragon_egg,scores={Timer=6000}] ~~~ detect ~~~ minecraft:daylight_detector_inverted 5 function egg/moonlight
execute @e[type=dragonmountsplus:phantom_dragon_egg,scores={Timer=6000}] ~~~ detect ~~~ minecraft:daylight_detector_inverted 6 function egg/moonlight
execute @e[type=dragonmountsplus:phantom_dragon_egg,scores={Timer=6000}] ~~~ detect ~~~ minecraft:daylight_detector_inverted 7 function egg/moonlight
execute @e[type=dragonmountsplus:phantom_dragon_egg,scores={Timer=6000}] ~~~ detect ~~~ minecraft:daylight_detector_inverted 8 function egg/moonlight
execute @e[type=dragonmountsplus:phantom_dragon_egg,scores={Timer=6000}] ~~~ detect ~~~ minecraft:daylight_detector_inverted 9 function egg/moonlight
execute @e[type=dragonmountsplus:phantom_dragon_egg,scores={Timer=6000}] ~~~ detect ~~~ minecraft:daylight_detector_inverted 10 function egg/moonlight
execute @e[type=dragonmountsplus:phantom_dragon_egg,scores={Timer=6000}] ~~~ detect ~~~ minecraft:daylight_detector_inverted 11 function egg/moonlight
execute @e[type=dragonmountsplus:phantom_dragon_egg,scores={Timer=6000}] ~~~ detect ~~~ minecraft:daylight_detector_inverted 12 function egg/moonlight
execute @e[type=dragonmountsplus:water_dragon_egg,scores={Timer=6000}] ~~~ detect ~~~ minecraft:daylight_detector_inverted 13 function egg/moonlight
execute @e[type=dragonmountsplus:phantom_dragon_egg,scores={Timer=6000}] ~~~ detect ~~~ minecraft:daylight_detector_inverted 14 function egg/moonlight
execute @e[type=dragonmountsplus:phantom_dragon_egg,scores={Timer=6000}] ~~~ detect ~~~ minecraft:daylight_detector_inverted 15 function egg/moonlight

execute @e[type=dragonmountsplus:phantom_dragon_egg,scores={Timer=6000}] ~~~ detect ~ ~-1 ~ minecraft:hardened_clay 0  execute @s ~ ~ ~ detect ~1 ~-1 ~ minecraft:hardened_clay 0 execute @s ~ ~ ~ detect ~-1 ~-1 ~ minecraft:hardened_clay 0 execute @s ~ ~ ~ detect ~ ~-1 ~1 minecraft:hardened_clay 0 execute @s ~ ~ ~ detect ~ ~-1 ~-1 minecraft:hardened_clay 0 execute @s ~ ~ ~ detect ~1 ~-1 ~1 minecraft:hardened_clay 0 execute @s ~ ~ ~ detect ~-1 ~-1 ~1 minecraft:hardened_clay 0 execute @s ~ ~ ~ detect ~1 ~-1 ~-1 minecraft:hardened_clay 0 execute @s ~ ~ ~ detect ~-1 ~-1 ~-1 minecraft:hardened_clay 0 function egg/terra

execute @e[type=dragonmountsplus:phantom_dragon_egg,scores={Timer=6000}] ~~~ detect ~ ~-1 ~ minecraft:bone_block 0 execute @s ~ ~ ~ detect ~1 ~-1 ~ minecraft:bone_block 0 execute @s ~ ~ ~ detect ~-1 ~-1 ~ minecraft:bone_block 0 execute @s ~ ~ ~ detect ~ ~-1 ~1 minecraft:bone_block 0 execute @s ~ ~ ~ detect ~ ~-1 ~-1 minecraft:bone_block 0 execute @s ~ ~ ~ detect ~1 ~-1 ~1 minecraft:bone_block 0 execute @s ~ ~ ~ detect ~-1 ~-1 ~1 minecraft:bone_block 0 execute @s ~ ~ ~ detect ~1 ~-1 ~-1 minecraft:bone_block 0 execute @s ~ ~ ~ detect ~-1 ~-1 ~-1 minecraft:bone_block 0 function egg/skeleton

execute @e[type=dragonmountsplus:phantom_dragon_egg,scores={Timer=6000}] ~~~ detect ~ ~-1 ~ minecraft:mossy_cobblestone 0  execute @s ~ ~ ~ detect ~1 ~-1 ~ minecraft:mossy_cobblestone 0 execute @s ~ ~ ~ detect ~-1 ~-1 ~ minecraft:mossy_cobblestone 0 execute @s ~ ~ ~ detect ~ ~-1 ~1 minecraft:mossy_cobblestone 0 execute @s ~ ~ ~ detect ~ ~-1 ~-1 minecraft:mossy_cobblestone 0 execute @s ~ ~ ~ detect ~1 ~-1 ~1 minecraft:mossy_cobblestone 0 execute @s ~ ~ ~ detect ~-1 ~-1 ~1 minecraft:mossy_cobblestone 0 execute @s ~ ~ ~ detect ~1 ~-1 ~-1 minecraft:mossy_cobblestone 0 execute @s ~ ~ ~ detect ~-1 ~-1 ~-1 minecraft:mossy_cobblestone 0 function egg/zombie

execute @e[type=dragonmountsplus:phantom_dragon_egg,scores={Timer=6000}] ~~~ detect ~ ~-1 ~ minecraft:ice 0 execute @s ~ ~ ~ detect ~1 ~-1 ~ minecraft:ice 0 execute @s ~ ~ ~ detect ~-1 ~-1 ~ minecraft:ice 0 execute @s ~ ~ ~ detect ~ ~-1 ~1 minecraft:ice 0 execute @s ~ ~ ~ detect ~ ~-1 ~-1 minecraft:ice 0 execute @s ~ ~ ~ detect ~1 ~-1 ~1 minecraft:ice 0 execute @s ~ ~ ~ detect ~-1 ~-1 ~1 minecraft:ice 0 execute @s ~ ~ ~ detect ~1 ~-1 ~-1 minecraft:ice 0 execute @s ~ ~ ~ detect ~-1 ~-1 ~-1 minecraft:ice 0 function egg/ice

execute @e[type=dragonmountsplus:phantom_dragon_egg,scores={Timer=6000}] ~~~ detect ~ ~-1 ~ minecraft:blue_ice 0  execute @s ~ ~ ~ detect ~1 ~-1 ~ minecraft:blue_ice 0 execute @s ~ ~ ~ detect ~-1 ~-1 ~ minecraft:blue_ice 0 execute @s ~ ~ ~ detect ~ ~-1 ~1 minecraft:blue_ice 0 execute @s ~ ~ ~ detect ~ ~-1 ~-1 minecraft:blue_ice 0 execute @s ~ ~ ~ detect ~1 ~-1 ~1 minecraft:blue_ice 0 execute @s ~ ~ ~ detect ~-1 ~-1 ~1 minecraft:blue_ice 0 execute @s ~ ~ ~ detect ~1 ~-1 ~-1 minecraft:blue_ice 0 execute @s ~ ~ ~ detect ~-1 ~-1 ~-1 minecraft:blue_ice 0 function egg/ice

execute @e[type=dragonmountsplus:phantom_dragon_egg,scores={Timer=6000}] ~~~ detect ~ ~-1 ~ minecraft:packed_ice 0  execute @s ~ ~ ~ detect ~1 ~-1 ~ minecraft:packed_ice 0 execute @s ~ ~ ~ detect ~-1 ~-1 ~ minecraft:packed_ice 0 execute @s ~ ~ ~ detect ~ ~-1 ~1 minecraft:packed_ice 0 execute @s ~ ~ ~ detect ~ ~-1 ~-1 minecraft:packed_ice 0 execute @s ~ ~ ~ detect ~1 ~-1 ~1 minecraft:packed_ice 0 execute @s ~ ~ ~ detect ~-1 ~-1 ~1 minecraft:packed_ice 0 execute @s ~ ~ ~ detect ~1 ~-1 ~-1 minecraft:packed_ice 0 execute @s ~ ~ ~ detect ~-1 ~-1 ~-1 minecraft:packed_ice 0 function egg/ice

execute @e[type=dragonmountsplus:phantom_dragon_egg,scores={Timer=6000}] ~~~ detect ~ ~-1 ~ minecraft:sand 0 execute @s ~ ~ ~ detect ~1 ~-1 ~ minecraft:sand 0 execute @s ~ ~ ~ detect ~-1 ~-1 ~ minecraft:sand 0 execute @s ~ ~ ~ detect ~ ~-1 ~1 minecraft:sand 0 execute @s ~ ~ ~ detect ~ ~-1 ~-1 minecraft:sand 0 execute @s ~ ~ ~ detect ~1 ~-1 ~1 minecraft:sand 0 execute @s ~ ~ ~ detect ~-1 ~-1 ~1 minecraft:sand 0 execute @s ~ ~ ~ detect ~1 ~-1 ~-1 minecraft:sand 0 execute @s ~ ~ ~ detect ~-1 ~-1 ~-1 minecraft:sand 0 function egg/terra

execute @e[type=dragonmountsplus:phantom_dragon_egg,scores={Timer=6000}] ~~~ detect ~ ~-1 ~ minecraft:red_sand 0  execute @s ~ ~ ~ detect ~1 ~-1 ~ minecraft:red_sand 0 execute @s ~ ~ ~ detect ~-1 ~-1 ~ minecraft:red_sand 0 execute @s ~ ~ ~ detect ~ ~-1 ~1 minecraft:red_sand 0 execute @s ~ ~ ~ detect ~ ~-1 ~-1 minecraft:red_sand 0 execute @s ~ ~ ~ detect ~1 ~-1 ~1 minecraft:red_sand 0 execute @s ~ ~ ~ detect ~-1 ~-1 ~1 minecraft:red_sand 0 execute @s ~ ~ ~ detect ~1 ~-1 ~-1 minecraft:red_sand 0 execute @s ~ ~ ~ detect ~-1 ~-1 ~-1 minecraft:red_sand 0 function egg/terra

execute @e[type=dragonmountsplus:phantom_dragon_egg,scores={Timer=6000}] ~~~ detect ~ ~-1 ~ minecraft:oak_leaves 8 execute @s ~ ~ ~ detect ~1 ~-1 ~ minecraft:oak_leaves 8 execute @s ~ ~ ~ detect ~-1 ~-1 ~ minecraft:oak_leaves 8 execute @s ~ ~ ~ detect ~ ~-1 ~1 minecraft:oak_leaves 8 execute @s ~ ~ ~ detect ~ ~-1 ~-1 minecraft:oak_leaves 8 execute @s ~ ~ ~ detect ~1 ~-1 ~1 minecraft:oak_leaves 8 execute @s ~ ~ ~ detect ~-1 ~-1 ~1 minecraft:oak_leaves 8 execute @s ~ ~ ~ detect ~1 ~-1 ~-1 minecraft:oak_leaves 8 execute @s ~ ~ ~ detect ~-1 ~-1 ~-1 minecraft:oak_leaves 8 function egg/forest

execute @e[type=dragonmountsplus:phantom_dragon_egg,scores={Timer=6000}] ~~~ detect ~ ~-1 ~ minecraft:oak_leaves 4 execute @s ~ ~ ~ detect ~1 ~-1 ~ minecraft:oak_leaves 4 execute @s ~ ~ ~ detect ~-1 ~-1 ~ minecraft:oak_leaves 4 execute @s ~ ~ ~ detect ~ ~-1 ~1 minecraft:oak_leaves 4 execute @s ~ ~ ~ detect ~ ~-1 ~-1 minecraft:oak_leaves 4 execute @s ~ ~ ~ detect ~1 ~-1 ~1 minecraft:oak_leaves 4 execute @s ~ ~ ~ detect ~-1 ~-1 ~1 minecraft:oak_leaves 4 execute @s ~ ~ ~ detect ~1 ~-1 ~-1 minecraft:oak_leaves 4 execute @s ~ ~ ~ detect ~-1 ~-1 ~-1 minecraft:oak_leaves 4 function egg/forest

execute @e[type=dragonmountsplus:phantom_dragon_egg,scores={Timer=6000}] ~~~ detect ~ ~-1 ~ minecraft:oak_leaves 0 execute @s ~ ~ ~ detect ~1 ~-1 ~ minecraft:oak_leaves 0 execute @s ~ ~ ~ detect ~-1 ~-1 ~ minecraft:oak_leaves 0 execute @s ~ ~ ~ detect ~ ~-1 ~1 minecraft:oak_leaves 0 execute @s ~ ~ ~ detect ~ ~-1 ~-1 minecraft:oak_leaves 0 execute @s ~ ~ ~ detect ~1 ~-1 ~1 minecraft:oak_leaves 0 execute @s ~ ~ ~ detect ~-1 ~-1 ~1 minecraft:oak_leaves 0 execute @s ~ ~ ~ detect ~1 ~-1 ~-1 minecraft:oak_leaves 0 execute @s ~ ~ ~ detect ~-1 ~-1 ~-1 minecraft:oak_leaves 0 function egg/forest

execute @e[type=dragonmountsplus:ender_dragon_egg,scores={Timer=6000}] ~~~ detect ~1 ~-1 ~ sculk 0 execute @s ~ ~ ~ detect ~-1 ~-1 ~ sculk 0 execute @s ~ ~ ~ detect ~ ~-1 ~1 sculk 0 execute @s ~ ~ ~ detect ~ ~-1 ~-1 sculk 0 execute @s ~ ~ ~ detect ~1 ~-1 ~1 sculk 0 execute @s ~ ~ ~ detect ~-1 ~-1 ~1 sculk 0 execute @s ~ ~ ~ detect ~1 ~-1 ~-1 sculk 0 execute @s ~ ~ ~ detect ~-1 ~-1 ~-1 sculk 0 function egg/sculk

execute @e[type=dragonmountsplus:ender_dragon_egg,scores={Timer=6000}] ~~~ detect ~1 ~-1 ~ sculk_catalyst 0 execute @s ~ ~ ~ detect ~-1 ~-1 ~ sculk_catalyst 0 execute @s ~ ~ ~ detect ~ ~-1 ~1 sculk_catalyst 0 execute @s ~ ~ ~ detect ~ ~-1 ~-1 sculk_catalyst 0 execute @s ~ ~ ~ detect ~1 ~-1 ~1 sculk_catalyst 0 execute @s ~ ~ ~ detect ~-1 ~-1 ~1 sculk_catalyst 0 execute @s ~ ~ ~ detect ~1 ~-1 ~-1 sculk_catalyst 0 execute @s ~ ~ ~ detect ~-1 ~-1 ~-1 sculk_catalyst 0 function egg/sculk

execute @e[type=dragonmountsplus:ender_dragon_egg,scores={Timer=6000}] ~~~ detect ~1 ~-1 ~ minecraft:prismarine 0 execute @s ~ ~ ~ detect ~-1 ~-1 ~ minecraft:prismarine 0 execute @s ~ ~ ~ detect ~ ~-1 ~1 minecraft:prismarine 0 execute @s ~ ~ ~ detect ~ ~-1 ~-1 minecraft:prismarine 0 execute @s ~ ~ ~ detect ~1 ~-1 ~1 minecraft:prismarine 0 execute @s ~ ~ ~ detect ~-1 ~-1 ~1 minecraft:prismarine 0 execute @s ~ ~ ~ detect ~1 ~-1 ~-1 minecraft:prismarine 0 execute @s ~ ~ ~ detect ~-1 ~-1 ~-1 minecraft:prismarine 0 function egg/guardian

execute @e[type=dragonmountsplus:water_dragon_egg,scores={Timer=6000}] ~~~ detect ~1 ~-1 ~ minecraft:prismarine 0 execute @s ~ ~ ~ detect ~-1 ~-1 ~ minecraft:prismarine 0 execute @s ~ ~ ~ detect ~ ~-1 ~1 minecraft:prismarine 0 execute @s ~ ~ ~ detect ~ ~-1 ~-1 minecraft:prismarine 0 execute @s ~ ~ ~ detect ~1 ~-1 ~1 minecraft:prismarine 0 execute @s ~ ~ ~ detect ~-1 ~-1 ~1 minecraft:prismarine 0 execute @s ~ ~ ~ detect ~1 ~-1 ~-1 minecraft:prismarine 0 execute @s ~ ~ ~ detect ~-1 ~-1 ~-1 minecraft:prismarine 0 function egg/guardian

execute @e[type=dragonmountsplus:fire_dragon_egg,scores={Timer=6000}] ~~~ detect ~1 ~-1 ~ minecraft:obsidian 0 execute @s ~ ~ ~ detect ~-1 ~-1 ~ minecraft:obsidian 0 execute @s ~ ~ ~ detect ~ ~-1 ~1 minecraft:obsidian 0 execute @s ~ ~ ~ detect ~ ~-1 ~-1 minecraft:obsidian 0 execute @s ~ ~ ~ detect ~1 ~-1 ~1 minecraft:obsidian 0 execute @s ~ ~ ~ detect ~-1 ~-1 ~1 minecraft:obsidian 0 execute @s ~ ~ ~ detect ~1 ~-1 ~-1 minecraft:obsidian 0 execute @s ~ ~ ~ detect ~-1 ~-1 ~-1 minecraft:obsidian 0 function egg/red

execute @e[type=dragonmountsplus:forest_dragon_egg,scores={Timer=6000}] ~~~ detect ~1 ~-1 ~ minecraft:obsidian 0 execute @s ~ ~ ~ detect ~-1 ~-1 ~ minecraft:obsidian 0 execute @s ~ ~ ~ detect ~ ~-1 ~1 minecraft:obsidian 0 execute @s ~ ~ ~ detect ~ ~-1 ~-1 minecraft:obsidian 0 execute @s ~ ~ ~ detect ~1 ~-1 ~1 minecraft:obsidian 0 execute @s ~ ~ ~ detect ~-1 ~-1 ~1 minecraft:obsidian 0 execute @s ~ ~ ~ detect ~1 ~-1 ~-1 minecraft:obsidian 0 execute @s ~ ~ ~ detect ~-1 ~-1 ~-1 minecraft:obsidian 0 function egg/red

execute @e[type=dragonmountsplus:ender_dragon_egg,scores={Timer=6000}] ~~~ detect ~1 ~-1 ~ minecraft:obsidian 0 execute @s ~ ~ ~ detect ~-1 ~-1 ~ minecraft:obsidian 0 execute @s ~ ~ ~ detect ~ ~-1 ~1 minecraft:obsidian 0 execute @s ~ ~ ~ detect ~ ~-1 ~-1 minecraft:obsidian 0 execute @s ~ ~ ~ detect ~1 ~-1 ~1 minecraft:obsidian 0 execute @s ~ ~ ~ detect ~-1 ~-1 ~1 minecraft:obsidian 0 execute @s ~ ~ ~ detect ~1 ~-1 ~-1 minecraft:obsidian 0 execute @s ~ ~ ~ detect ~-1 ~-1 ~-1 minecraft:obsidian 0 function egg/red

